let colors = ["Red", "Green", "Blue"];
document.write("Original Colors: " + colors + "<br><br>");
let colorStart = prompt("Enter a color to add at the beginning:");
colors.unshift(colorStart);
document.write("After adding at beginning: " + colors + "<br><br>");
let colorEnd = prompt("Enter a color to add at the end:");
colors.push(colorEnd);
document.write("After adding at end: " + colors + "<br><br>");
colors.unshift("Purple", "Orange");
document.write("After adding two colors at beginning: " + colors + "<br><br>");
colors.shift();
document.write("After deleting first color: " + colors + "<br><br>");
colors.pop();
document.write("After deleting last color: " + colors + "<br><br>");
let indexAdd = prompt("At which index do you want to add a color?");
let colorName = prompt("Enter the color name to add:");
colors.splice(indexAdd, 0, colorName);
document.write("After adding at index " + indexAdd + ": " + colors + "<br><br>");
let indexDelete = prompt("At which index do you want to delete color(s)?");
let deleteCount = prompt("How many colors do you want to delete?");
colors.splice(indexDelete, deleteCount);
document.write("After deleting from index " + indexDelete + ": " + colors + "<br><br>");